[pytest]
addopts = --alluredir=allure-results --video retain-on-failure --screenshot on

#[pytest-playwright]
#video = retain-on-failure
#screenshot = only-on-failure
#trace = retain-on-failure


markers =
    smoke: Smoke tests
    regression: Regression tests
    sanity: Sanity tests

testpaths = tests
pythonpath = .